#!/bin/bash

# Generate "real" data using "fine" data and Matrix-vector multiplication
# NOTE: set envirenment variables for different variables
#       remap addunits4field meta are all binary executable generated by GEM makefile
# Author: pinewall

physical_variable="avXa2c_a_Sa_ptem"
#physical_variable="avXa2c_a_Sa_tbot"
remap_algorithm_phase1="conserv"
remap_algorithm_phase2="conserv"
remap_tags="${remap_algorithm_phase1}_${remap_algorithm_phase2}"
finedata_path="../fine"

# Check file existence
if [ -f ${finedata_path}/${physical_variable}.fine.nc ] 
then

    # Using remap binary to generate "real" physical variable distribution on test grids
    if [ -f rmp_ll0.5_to_T42_conserv.nc ]
    then
        echo "Generate real data for T42 grid"
    else
        echo "rmp_ll0.5_to_T42_conserv.nc does NOT exist!"
    fi
    #./remap ${finedata_path}/${physical_variable}.fine.nc rmp_ll0.5_to_T42_conserv.nc ${physical_variable}.${remap_tags}.T42.nc

    if [ -f rmp_ll0.5_to_licom1x1_conserv.nc ]
    then
        echo "Generate real data for licom1x1 grid"
    else
        echo "rmp_ll0.5_to_licom1x1_conserv.nc does NOT exist!"
    fi
    #./remap ${finedata_path}/${physical_variable}.fine.nc rmp_ll0.5_to_licom1x1_conserv.nc ${physical_variable}.${remap_tags}.licom1x1.nc

    if [ -f rmp_ll0.5_to_POP43_conserv.nc ]
    then
        echo "Generate real data for POP43 grid"
    else
        echo "rmp_ll0.5_to_POP43_conserv.nc does NOT exist!"
    fi
    #./remap ${finedata_path}/${physical_variable}.fine.nc rmp_ll0.5_to_POP43_conserv.nc ${physical_variable}.${remap_tags}.POP43.nc

    if [ -f rmp_ll0.5_to_gamil360x180_conserv.nc ]
    then
        echo "Generate real data for gamil360x180 grid"
    else
        echo "rmp_ll0.5_to_gamil360x180_conserv.nc does NOT exist!"
    fi
    #./remap ${finedata_path}/${physical_variable}.fine.nc rmp_ll0.5_to_gamil360x180_conserv.nc ${physical_variable}.${remap_tags}.gamil360x180.nc

    if [ -f rmp_ll0.5_to_ll1_conserv.nc ]
    then
        echo "Generate real data for ll1 grid"
    else
        echo "rmp_ll0.5_to_ll1_conserv.nc does NOT exist!"
    fi
    #./remap ${finedata_path}/${physical_variable}.fine.nc rmp_ll0.5_to_ll1_conserv.nc ${physical_variable}.${remap_tags}.ll1.nc

    if [ -f rmp_ll0.5_to_ll2.5_conserv.nc ]
    then
        echo "Generate real data for ll2.5 grid"
    else
        echo "rmp_ll0.5_to_ll2.5_conserv.nc does NOT exist!"
    fi
    #./remap ${finedata_path}/${physical_variable}.fine.nc rmp_ll0.5_to_ll2.5_conserv.nc ${physical_variable}.${remap_tags}.ll2.5.nc

    # Add attributes
    #./addunits4field ${physical_variable}.${remap_tags}.T42.nc
    #./addunits4field ${physical_variable}.${remap_tags}.POP43.nc
    #./addunits4field ${physical_variable}.${remap_tags}.gamil360x180.nc
    #./addunits4field ${physical_variable}.${remap_tags}.licom1x1.nc
    #/addunits4field ${physical_variable}.${remap_tags}.ll1.nc
    #/addunits4field ${physical_variable}.${remap_tags}.ll2.5.nc

    # Generate XML meta data for later usage
    #/meta ${physical_variable}.${remap_tags}.T42.nc ${physical_variable}.${remap_tags}.T42.xml
    #/meta ${physical_variable}.${remap_tags}.POP43.nc ${physical_variable}.${remap_tags}.POP43.xml
    #/meta ${physical_variable}.${remap_tags}.gamil360x180.nc ${physical_variable}.${remap_tags}.gamil360x180.xml
    #/meta ${physical_variable}.${remap_tags}.licom1x1.nc ${physical_variable}.${remap_tags}.licom1x1.xml
    #/meta ${physical_variable}.${remap_tags}.ll1.nc ${physical_variable}.${remap_tags}.ll1.xml
    #/meta ${physical_variable}.${remap_tags}.ll2.5.nc ${physical_variable}.${remap_tags}.ll2.5.xml
else
    echo "${physical_variable}.fine.nc does NOT exist!"
    exit 1
fi
